### ISSUE TITLE
sqladmin/v1beta4 Incorrect field name while filtering

### ISSUE THREAD

**Issue by kk-pp** [googleapis/google-api-go-client#349]
How to filter the database version field when listing the instances? I used DATABASE_VERSION:MYSQL* and it returned an error saying that DATABASE_VERSION field does not exist

**Comment by broady** [comment]
Can you paste a small piece of code so we can help reproduce?

/cc @kurtisvg

**Comment by kurtisvg** [comment]
@kkpsychpress The correct field name is `databaseVersion`. You can find a list of field names for 'instances' objects [here](https://cloud.google.com/sql/docs/postgres/admin-api/v1beta4/instances#resource). 

If you wanted to get all MySQL versions, you could use the following filter string: `databaseVersion~MYSQL.*`.

**Comment by kkpsychpress** [comment]
Hi @broady  @kurtisvg 

I tried it here https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/instances/list
it's still returning 400

here's my code in go:
```
req := sqlService.Instances.List("gosecure").Filter("databaseVersion:MYSQL*")
```

I tried `databaseVersion~MYSQL.*` but it says invalid token `~`. Am I missing something here?

I'm using `google.golang.org/api/sqladmin/v1beta4@master`

**Comment by kurtisvg** [comment]
@kkpsychpress You aren't missing anything at all. I made the mistake of checking with the gcloud tool, which apparently filters on the client side instead of using the query parameter. So the following gcloud line does what we were expecting:
```
gcloud sql instances list --filter='databaseVersion=MYSQL.*'
```

Unfortunately, there is a bug in the API that's exposing the resource fields improperly. I've filed an internal bug to make sure it get's addressed. If you need a solution now and filtering client side isn't acceptable, you can use `database_type=MYSQL_5_6 OR database_type=MYSQL_5_7` (but be warned this is unintended behavior and will stop working when the bug is fixed).

**Comment by mkobetic** [comment]
Would this be the same issue for my failure?

`Invalid request: Bad instance filter [instanceType=ON_PREMISES_INSTANCE AND name:mk-test-db1-us-east1], error: com.google.cloud.api.filter.EvaluatorException: Field not found. In expression instanceType EQUALS ON_PREMISES_INSTANCE, At field instanceType ., invalid`

`instanceType` seems to be a correct field AFAICS.

**Comment by daddyfatstaks** [comment]
Hey Russian why don't you make like a 🌲 and leave. For good. Give it up
man. You lose. Don't be a sore loser. Have some class and keep your
integrity. Stop trying to take something back that you gave to the public
because someone else did something you didn't think of first. You're being
a crybaby.

**Comment by kurtisvg** [comment]
@mkobetic This is probably the same issue -- I'm trying to look into and find out what the correct field is, and hopefully can update you here in a couple of days.

**Comment by jadekler** [comment]
For posterity, we're tracking this in internal bug 80491527.

**Comment by eahrend** [comment]
Hey, I was requested to post this issue here as well.

Hey, I'm attempting to filter a list of databases based on the name parameter.

req := sqladminService.Instances.List(project).Filter("name:my-database")
    if err := req.Pages(ctx, func(page *sqladmin.InstancesListResponse) error {
            for _, databaseInstance := range page.Items {
		fmt.Printf("%+v\n", databaseInstance)				
            }
            return nil
    });
I've attempted to change the filter query to "name=my-database" and no results show up. When I remove the filter the database will show up in the response.

Here is the (heavily redacted) response I get.

{
    "backendType": "SECOND_GEN",
    "kind": "sql#instance",
    "name": "my-database"
}
When attempting other filters like backendType=SECOND_GEN it will still fail to produce any results, however doing something like name!=my-database will show all results.

Is there something I am missing or is this a bug in the beta? We can get around this issue currently by iterating over the list of databases and comparing the databaseInstance.Name parameter, however it's not ideal if we can filter before parsing the list.

**Comment by kurtisvg** [comment]
@mkobetic I've heard back from the team and unfortunately it doesn't look like it's possible to filter based on `instanceType` at the moment. 

@eahrend Just to confirm, the Cloud SQL Admin API itself does currently have a bug in instance filtering.

**Comment by mkobetic** [comment]
> @mkobetic I've heard back from the team and unfortunately it doesn't look like it's possible to filter based on `instanceType` at the moment.

Thank you for looking into it.

**Comment by eahrend** [comment]
@kurtisvg Thanks for the update, we're currently working around this via iterating over the instances in order to get the ones we're looking for.

**Comment by kurtisvg** [comment]
Cloud SQL Issue tracker bug [here](https://buganizer.corp.google.com/issues/136025195) for anyone that wants to be notified of the resolution.

**Comment by kurtisvg** [comment]
I just verified this is now fixed.

**Comment by jadekler** [comment]
Thanks @kurtisvg !

**Comment by moos3** [comment]
I'm still seeing this issue. Can you please provide a non-moma link for the resolution on this.

**Comment by d1egoaz** [comment]
Hey @kurtisvg I wonder if you could please share the status of the internal bug report.

As today I'm getting the same issue reported above.

```go
sqladmin "google.golang.org/api/sqladmin/v1"
...
req := service.Instances.List(ProjectID).Filter("(labels.xxx-yyy=true)")
```

```
2022/11/01 11:32:02 googleapi: Error 400: Invalid request: Bad instance filter [(labels.xxx-yyy=true)], error: com.google.cloud.api.filter.EvaluatorException: Field not found. In expression labels.xxx-yyy EQUALS true, At field labels ., invalid

```

**Comment by enocom** [comment]
The label syntax is a little tricky. Try this:

``` golang
resp, err := svc.Instances.List(projectID).Filter("settings.userLabels.key1:val2").Do()
```

**Comment by d1egoaz** [comment]
> The label syntax is a little tricky. Try this:
> 
> ```go
> resp, err := svc.Instances.List(projectID).Filter("settings.userLabels.key1:val2").Do()
> ```

That worked! thanks!

I guess the confusion is the different syntax between gcloud and the different rest APIs.

I actually just found that this is documented in https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1/instances/list
> Fields can be nested as needed as per their JSON representation, such as 'settings.userLabels.auto_start:true'.

**Comment by d1egoaz** [comment]
@enocom do you happen to know where I can get more info/docs about filtering dates using the cloudsql rest api?


I'm currently filtering an string label in gcloud using:
```
labels.xxx<2022-10-01
```

However, when using the filter in the API via: `settings.userLabels.xxx<'2022-10-01'`, or `settings.userLabels.xxx<2022-10-01`:

I'm getting the following errors:

```
, error: com.google.cloud.api.filter.EvaluatorException: Lexical comparison of strings not supported. In expression settings.userLabels.xxx LESS_THAN '2022-10-01'


error: com.google.cloud.api.filter.EvaluatorException: Lexical comparison of strings not supported. In expression settings.userLabels.xxx LESS_THAN 2022-10-01, 
```

If I use `settings.userLabels.last-seen-time<'2022-10-01T12:00:00'` I got a parser exception.

Thanks

**Comment by enocom** [comment]
This is the best documentation I know of: https://github.com/googleapis/google-api-go-client/blob/main/sqladmin/v1/sqladmin-gen.go#L8215-L8223.

I don't see any signs that this filter expression supports anything but equality, though.

**Comment by d1egoaz** [comment]
> 

Thanks for checking! I'll keep doing the date filtering locally.
